# https://taskfile.dev

version: "3"

tasks:
  build-wasm:
    cmds:
      - wasm-pack build --target web --no-typescript --no-pack -d static/wasm uml-wasm

  run:
    deps: [build-wasm]
    cmds:
      - cargo run --package uml-server

  watch:
    env:
      RUST_LOG: '{{.RUST_LOG | default "actix_server=info,uml_server=debug"}}'
    cmds:
      - watchexec --stop-signal=SIGINT -re rs,js -w Taskfile.yml -w uml-server/src -w uml-common/src -w uml-wasm/src go-task run

  build-docker:
    cmds:
      - docker buildx build -t uml .

  save-docker:
    deps: [build-docker]
    cmds:
      - docker save uml | gzip > uml-docker.tar.gz

  run-docker:
    deps: [build-docker]
    env:
      RUST_LOG: '{{.RUST_LOG | default "actix_server=info,uml_server=debug"}}'
    cmds:
      - docker run --rm -it -p 8080:8080 --name uml -e RUST_LOG=${RUST_LOG} uml
